server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

# Spring Security configuration


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level.org.hibernate.SQL: debug            # 로그 형식으로 쿼리 보여주기
spring.jpa.properties.hibernate.format_sql: true  # 압축된 쿼리를 읽기 좋게 포멧
# spring.jpa.hibernate.ddl-auto: create             # 서버 시작에 테이블 생성